# Blog info
blog_name: RoidderğŸ™„ï¸
slogan: æ‚Ÿä»¥å¾€ä¹‹ä¸è°ï¼ŒçŸ¥æ¥è€…ä¹‹å¯è¿½
url: https://nunchakus888.github.io

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: Javascript,Nunchakus,Tricking,Kufu

home_nav:
  - name: ä¸€ç¯‡è¯—
    url: /archives
    target_blank: false
  - name: ä¸€å£¶é…’
    url: /category
    target_blank: false
  - name: ä¸€æ›²é•¿æ­Œ
    url: /tags
    target_blank: false
  - name: ä¸€å‰‘å¤©æ¶¯
    url: https://github.com/nunchakus888
    target_blank: true

# config page nav
page_nav:
  - name: ğŸ™„ï¸
    url: /
    target_blank: false # ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: ä¸€ç¯‡è¯—
    url: /archives
    target_blank: false
  - name: ä¸€å£¶é…’
    url: /category
    target_blank: false
  - name: ä¸€æ›²é•¿æ­Œ
    url: /tags/
    target_blank: false
  - name: ä¸€å‰‘å¤©æ¶¯
    url: /about/
    target_blank: false
#  - name: RSS
#    url: /atom.xml
#    target_blank: true # åœ¨æ–°é¡µé¢æ‰“å¼€


baidu_analytics:

disqus_shortname: aqua
